estesp/manifest-tool

- docker/inspect.go
Fixes https://github.com/estesp/manifest-tool/issues/3
> only log username

- docker/inspect_test.go
- docker/util_test.go
Signed-off-by: Mathew Koshy <mathewkoshy493@gmail.com>
> Adding unit test for util.go.

- main.go
> Bump release to 0.5.0

- main.go
> Bump version to 0.6.0 for release

- README.md
Significant updates to the documentation; add examples for all command
types and clarify/clean up wording.
Fixes: #15
> Update README.md with clearer/updated documentation

- docker/createml.go
Fix the problem where library/xxx repos on DockerHub cannot be pushed to
because of name normalization in the reference package code.
This is solved by building custom URLs for manifest and blob upload
references when `library/` references are used and the hostname matches
the canonical DockerHub registry reference.
Fixes: #47
> Allow push to library/xxx via custom URL builder

- README.md
- main.go
Update version and add README content on the v0.7.0 changes/release.
> Prepare v0.7.0 release

- main.go
> Bump post-release version number

- docker/createml.go
Fixes #55 
Check was incorrect due to target reference being created without a
hostname (after being split into hostname and repo:tag components to be
exact). This caused any non-repo delineated name to be associated with
the default DockerHub registry hostname and therefore caused the check
to incorrectly associate such names as being library references.
> Fix check for DockerHub "library" reference

- docker/util.go
> Add windows/arm to the validOSArch map

- main.go
> Prepare v0.9.0 release

- main.go
Master will reflect development leading up to a potential v1.0.0 release
in the future.
> Master branch update to post-v0.9.0 release

- main.go
Correct added fix for --insecure
> Prepare v1.0.0-rc3

- .travis.yml
- Dockerfile
- Makefile
- appveyor.yml
- main.go
> Update all to Go 1.13

- main.go
> Prepare final v1.0.0 release

- integration/test-registry.yml
> Fix variant string for arm

- main.go
> Prepare v1.0.2 release

- README.md
Add documentation for using VARIANT, had to dig through the code for this, but this is exactly what I needed!
> Add VARIANT Documentation

- main.go
Make a release to fix the reference push issue introduced several
releases ago; affects Artifactory
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
> Prepare v1.0.3

- .github/workflows/ci.yml
> Update main branch

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
- hack/cross.sh
- pkg/util/os_test.go
> Update to Go 1.16

- cmd/manifest-tool/push.go
> Add push output to match v1.x for backwards compat

- .github/workflows/release.yml
- cmd/manifest-tool/main.go
Prepare for a beta release of the v2 codebase.
> Prepare v2.0.0-beta.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update Go version for project CI and releases

- v2/cmd/manifest-tool/inspect.go
> Add a more helpful error if the inspected ref has no tag

- v2/cmd/manifest-tool/main.go
> Prepare v2.0.0-rc.1 release

- .github/workflows/ci.yml
- .github/workflows/release.yml
- hack/cross.sh
Also update to Go 1.17.5
Fixes: #138
> Add cross-build for macOS + arm64 (M1)

- v2/go.mod
- v2/go.sum
- v2/vendor/modules.txt
> Update vendor for runc

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update Go to 1.17.7

- .github/workflows/release.yml
- .gitignore
- hack/Dockerfile.linux
- hack/Dockerfile.windows2016
- hack/makestatic.sh
- hack/pushml-pre.yaml
- hack/pushml.yaml
Mostly copied from the way mquery does this in GitHub Actions already.
> Add DockerHub deployment to release scripts

- README.md
- v2/cmd/manifest-tool/main.go
> Prepare for final v2.0.0 release

- v2/cmd/manifest-tool/main.go
> Main is now dev for next 2.0.x release

- integration/test-registry.sh
Cleanup test script; mis-numbering and an assumption about host platform
> Update test script

- v2/cmd/manifest-tool/main.go
> Prepare patch release v2.0.1

- v2/cmd/manifest-tool/main.go
> Update main branch to -dev version

- v2/cmd/manifest-tool/inspect.go
- v2/cmd/manifest-tool/main.go
- v2/cmd/manifest-tool/push.go
> Properly fix path/file handling for the --docker-cfg flag

- .github/workflows/release.yml
- hack/Dockerfile.alpine
- hack/pushml-alpine.yaml
Closes https://github.com/estesp/manifest-tool/issues/165
> Add alpine base image

- v2/cmd/manifest-tool/main.go
> Prepare v2.0.4 release

- v2/cmd/manifest-tool/main.go
> Update main to post-2.0.4 version

- v2/go.mod
- v2/vendor/modules.txt
> Remove final replace rule in go.mod

- v2/cmd/manifest-tool/main.go
> Prepare for v2.0.5 release

- v2/cmd/manifest-tool/main.go
> Post release make main branch -dev for the next release

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Update deprecated Nodejs 12 actions

- .github/workflows/release.yml
> Update Go version in release.yml

- v2/go.mod
- v2/go.sum
- v2/vendor/github.com/containerd/containerd/platforms/defaults_windows.go
- v2/vendor/github.com/containerd/containerd/version/version.go
- v2/vendor/modules.txt
Update to latest containerd release
> Update containerd vendor

- v2/cmd/manifest-tool/inspect.go
Properly handle the new use of indexes to include references to attestations created by tools like BuildKit in its recent 0.11 release.
> Update inspect to handle attestations

- v2/cmd/manifest-tool/main.go
> Prepare to release v2.0.7

- v2/cmd/manifest-tool/main.go
Set version to 2.0.9-dev until next release
> Move main to 2.0.9-dev version

- v2/cmd/manifest-tool/inspect.go
Fixes: #223
Complete the implementation of outputting JSON when using the --raw flag on inspect
> Output proper/complete JSON with --raw

- v2/cmd/manifest-tool/inspect.go
Fixes: #222
Expands the image config object in raw JSON output to allow easier inspection of image details.
> feat: Add --expand-config flag to --raw output

- .codespellrc
- .github/workflows/codespell.yml
- v2/pkg/registry/pusher.go
> Add codespell: config, workflow (to alert when new typos added) and get typos fixed

- v2/cmd/manifest-tool/inspect.go
> Allow inspect to support digests instead of only tags
