estesp/manifest-tool

- docker/createml.go
- docker/inspect.go
- inspect.go
Implement cross-repo push via blob mounting from source images in the YAML manifest that are not in the target repository.
Allows things like "busybox_x86_64:latest" to be used as a source for target "busybox:latest", as an example.
> Cross repository push implemented

- docker/createml.go
- docker/inspect.go
- docker/inspect_v2.go
- types/types.go
To fully support cross-repository push we must ask for the blobs to be
mounted, but we must also push the manifests referenced into the target
namespace so that the manifest list push finds all its digest
references.  The config reference (in v2.2 spec) must also be added as a
blob mount request since it is referred to in the manifest we now push.
> Add push of manifest and config (for v2.2) references

- docker/inspect.go
- docker/inspect_v2.go
- inspect.go
Now outputs the manifest list digest as part of the
inspect output.
> Show manifest list digest/info in inspect

- main.go
I updated the `version` string to `0.4.0-dev`, but I'm happy to modify if you'd rather it be something else (but I figured that now that `0.4.0` is out, `0.3.0` probably isn't the right value to be in there anymore :smile:).
> Update "version" string

- docker/inspect.go
- docker/inspect_v2.go
Get rid of v1 endpoint ping (unecessary, as the entire support for
manifest lists requires a v2 endpoint anyway) and gracefully handle
potential registry limitations on getting all tag list. The IBM Bluemix
registry currently blocks the "list all tags" API endpoint, but it is
not required for inspect, as it just limits the output data in a small
way.
> Better handling of v2-only registry interaction

- README.md
- docker/createml.go
Finally implemented that TODO item in the README (since looking at the code, it seemed relatively simple to plug in to the existing "inspect" logic at push-time).
> Automatically populate OS and architecture from source manifests (if unspecified)

- docker/createml.go
- docker/inspect.go
- main.go
- push.go
Enable an `--ignore-missing` parameter to the push subcommands that will
ignore any missing entries in YAML or provided os/arch list on the
command line. This allows a consistent YAML or command line to be used
and only do a "best effort" push of a manifest list depending on how
many of the source images are available at the time. If none are
available the push fails, understandably.
Fixes: #22 
Closes: #13
> Support ignore-missing behavior

- docker/createml.go
- types/types.go
Provide the ability to add "tags: [ .. ]" to the input YAML with a list
of additional tags to push to the registry against the manifest list
object being pushed.
Fixes: #23 
And..seems to work :)
```
DEBU[0009] [extra tag "1.8"] push url: https://registry-1.docker.io/v2/estesp/bbimg/manifests/1.8
DEBU[0010] [extra tag "fred"] push url: https://registry-1.docker.io/v2/estesp/bbimg/manifests/fred
DEBU[0010] [extra tag "wilma"] push url: https://registry-1.docker.io/v2/estesp/bbimg/manifests/wilma
DEBU[0011] [extra tag "1.8-alpine"] push url: https://registry-1.docker.io/v2/estesp/bbimg/manifests/1.8-alpine
DEBU[0011] [extra tag "wilson-99"] push url: https://registry-1.docker.io/v2/estesp/bbimg/manifests/wilson-99
Digest: …
```
> Allow extra tags to be provided for tagging the manifest list

- docker/createml.go
Incorrectly using the full URL during manifest reference push code
instead of splitting out hostname. Recent testing with only DockerHub
had missed this case.
Fixes: #34 
Fixes: #33
> Fix manifest reference URL creation for private registries

- Makefile
- main.go
Add commit info (+dirty flag) to version output. Bump to 0.6.0-dev to
differentiate from 0.6.0 released version.
> Add version detail; bump to 0.6.0-dev

- Makefile
- hack/Dockerfile.linux-amd64
- hack/Dockerfile.linux-arm
- hack/Dockerfile.linux-arm64
- hack/Dockerfile.linux-ppc64le
- hack/Dockerfile.linux-s390x
- hack/cross.sh
Create static binaries; also include commit information in the `make
cross` target. Add Dockerfile instances for all Linux architectures in
preparation of having an easy to use multi-platform image to test
`manifest-tool` on any architecture.
> Create static binaries by default on Linux

- README.md
Add details to the README about using the test script to validate an
image registry supports the manifest-list media type and Docker
distribution V2 APIs required for dealing with manifest lists.
> Add details on the test script in `integration/`

- README.md
manifest-tool can't use the osxkeychain, so clear up how authentication
is handled in the README documentation, and add an important note about
Docker for Mac since 17.03 release.
Fixes: #42
> Specify Docker for Mac use of osxkeychain impact

- docker/createml.go
- docker/inspect_v2.go
- push.go
To sign a manifest, `notary` needs to know the length of the manifest. The first commit passes this information from from `PushManifest` back to `push` where it is printed out. This has been tested and is now already the default with linuxkit, where we now push signed manifests.
The other two commits are cosmetic `golint` and `ineffassign` fixes to allow us to build `manifest-tool` with the LinuxKit tooling. I can split this into a separate PR if desired
> Print lenght of manifest for notary signing

- README.md
This was pointed out by @funkyfuture over in https://github.com/estesp/manifest-tool/pull/32#issuecomment-319938701 so I figured I'd take a crack at a first pass. :smile:
> Add a short README blurb about "tags"

- Makefile
This prevents "-X flag requires argument of the form importpath.name=value"
error from go when doing "make build" (at least on Debian, Docker 17.06.1,
GNU Make 4.0)
> Escape quotes around -ldflags.

- Makefile
- README.md
- hack/cross.sh
Modify `binary` target to match `build` target to build a standard,
dynamically-linked executable; one via Dockerfile, one via local system.
Add `static` target to properly build a static binary, and correct
`hack/cross.sh` script to also build proper static binaries.
> Fix static and non-static targets in Makefile

- Dockerfile
- hack/cross.sh
This also updates `Dockerfile` to Go 1.9 (as in https://github.com/estesp/manifest-tool/pull/48) to avoid the privilege of having to deal with https://github.com/golang/go/issues/9737#issuecomment-276817652.
Sample output:
```console
$ make shell
docker build  -t "estesp/manifest-tool-dev:goarm" .
Sending build context to Docker daemon  103.2MB
Step 1/8 : FROM golang:1.9
---> bba10fd6d576
Step 2/8 : ENV GO_TOOLS_COMMIT 823804e1ae08dbb14eb807afc7db9993bc9e3cc3
---> Using cache
---> bed437ce0cee
Step 3/8 : RUN git clone https://github.com/golang/tools.git /go/src/golang.org/x/tools 	&& (cd /go/src/golang.org/x/tools && git checkout -q $GO_TOOLS_COMMIT) 	&& go install -v golang.org/x/tools/cmd/cover 	&& go install -v golang.org/x/tools/cmd/vet
---> Using cache
---> 0782f10f6d01
Step 4/8 : …
```
> Update "hack/cross.sh" to set "GOARM" appropriately (and build for more ARM variants)

- README.md
Add a section in the README on using mplatform/mquery instead of having
to install the manifest-tool binary to do simple query operations.
> Add info on the mquery tool

- README.md
Also update text re: docker/cli PR for `docker manifest` to report that
the manifest subcommand is now merged and available in the Docker
client project.
> Add information on known supporting registries

- docker/createml.go
GitLab and potentially other registries may not handle "*" properly as
the requested permissions; explicitly ask for "push" and "pull"
Fix brought in from docker/cli#1024 thanks @clnperez :)
Fixes: #53
> Fix use of * for permissions request on token auth

- docker/createml.go
- docker/inspect.go
- inspect.go
- main.go
- push.go
Add necessary support as well as an `--insecure` flag for manifest-tool
to be able to interact with non-TLS registry endpoints (or self-signed
certs untrusted by the client-side)
Fixes: #14 
> Add support for http/insecure registries

- docker/inspect_v2.go
Fixes: #74 
Fix the v1 image fetch to properly list layers for inspect.
> Add proper support for inspect of v1 image manifest

- docker/createml.go
- docker/util.go
- docker/util_test.go
- push.go
- types/types.go
Adds support for `variant` for image manifest.
`arm` architectures have several different variants that are apart of the image manifest system.
Resolves Issue #71
> adds support for variants in the from-args feature

- .travis.yml
- appveyor.yml
- hack/Dockerfile.linux
- hack/Dockerfile.linux-amd64
- hack/Dockerfile.linux-arm
- hack/Dockerfile.linux-arm64
- hack/Dockerfile.linux-ppc64le
- hack/Dockerfile.linux-s390x
- hack/Dockerfile.windows
Adds a manifest list image of manifest-tool itself on DockerHub for
versioned pushes; located at mplatform/manifest-tool
Closes: #73 
> Add autobuild of manifest list images

- docker/createml.go
- docker/inspect.go
Apply insecure setting to choosing endpoints.
Applies to: #14 
When you use a local registry like `docker run -p 5000:5000 registry:2` but specify the actual IP address (not localhost or 127.0.0.1), the `Index.Secure` setting for a `repoInfo` struct is actually not correct. The solution to that would be a deeper set of fixes to utilizing the `docker/docker` imports around registry config versus writing/copying into `manifest-tool`; a workaround is simply to ignore `Index.Secure` for a repo, and use the flag of our tool to override endpoint selection ordering, and pick the **http** proto endpoint.
> Fix insecure for http-only endpoints

- appveyor.yml
- hack/Dockerfile.windows
- main.go
Update version; specific focus is on re-building with latest Go 1.13
release to fix a potential s390x bug ( #86 ) and apply all Golang fixes in the Go 1.13
release history from 1.13.0 -> 1.13.8
> Prepare v1.0.1 release

- docker/createml.go
- docker/inspect.go
- docker/inspect_v2.go
- inspect.go
For images with a lot of tags it can take a significant amount of time to
list tags.  This can often cause timeouts causing the operation to fail
or if ignore-missing is set wrongly skip an image.  This change will only
grab tags during "inspect --raw" and not during non-raw inspect or push.
Since some repos are so large they always timeout a new parameter --tags
has been added to inspect do disable including tags on raw inspect.
> Only optionally grab repotags in raw inspect out

- docker/createml.go
Fix: #98 
This should solve the issue of pushing to a tag accidentally instead of the digested reference for manifest references.
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
> Drop potential tag from digested ref for manifest refs

- docker/inspect.go
This uses GetAuthConfig from github.com/docker/cli, which embeds logic
for handling credential helpers.
I was surprised that manfiest-tool didn't work with credential helpers when I tried it! :)
You may want to clean this up a bit more by just reading the config file once [here](https://github.com/estesp/manifest-tool/blob/505479b95ee682b7302a76e86f3b913d506ab3fc/push.go#L129-L135) and passing it around, but I wanted to keep the diff small to avoid breaking anything.
Fixes https://github.com/estesp/manifest-tool/issues/92
> Enable use of credential helpers

- go.sum
- pkg/registry/push.go
Short Issue Description
```bash
$ manifest-tool push from-spec manifest.yaml 
WARN[0000] Error loading auth file: /home/nfox/.docker/config.json/config.json: stat /home/nfox/.docker/config.json/config.json: not a directory 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x89371c]
```
More details
`config.json` is treated as a directory that leads to a go-panic. As a workaround, it's still possible to create  ~/.docker/config.json/ directory and put there config.json => ~/.docker/config.json/config.json.
Unfortunately, I haven't found test cases so I might have fixed the wrong place, but it works well now.
> Fix config.json file locating

- integration/test-registry-tag.yml
- integration/test-registry-tagonly.sh
Instead of pushing different image names for the registry test, allow a
variant which only uses tags to differentiate into a single image
repository.
> Add ability to test pushing an index using only tags

- pkg/registry/fetcher.go
- pkg/registry/push.go
- pkg/registry/pusher.go
- pkg/types/image.go
The "2.x" manifest-tool codebase hadn't yet been tested with Windows image references that had foreign/non-distributable layers. The generic push content code being used from containerd doesn't filter on foreign layers so it required that we filter out those references before calling `PushContent` so that manifest lists with Windows image references can be pushed successfully to a registry.
> Fix push with Windows foreign layer references

- pkg/registry/push.go
- pkg/types/image.go
When using a YAML file that doesn't include `platform:` objects at all, the following is the result:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8aa679]
goroutine 1 [running]:
github.com/estesp/manifest-tool/pkg/registry.resolvePlatform(0xc000568840, 0x34, 0xc000578b90, 0x47, 0x20f, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/estesp/manifest-tool/pkg/registry/push.go:126 +0xb9
github.com/estesp/manifest-tool/pkg/registry.PushManifestList(0x0, 0x0, 0x0, 0x0, 0xc00045a168, 0x15, 0x0, 0x0, 0x0, 0xc00040aa80, ...)
/go/src/github.com/estesp/manifest-tool/pkg/registry/push.go:92 +0xdfb
main.glob..func2(0xc00044c420)
/go/src/github.com/estesp/manifest-tool/cmd/manifest-tool/push.go:55 +0x3cf …
```
> Fix segfault and add (optional) variant in image config

- v2/pkg/store/store.go
We use `manifest-tool` and stumbled upon the issue with concurrent map read/write. I've added `sync.RWMutex` to fix it.
```
fatal error: concurrent map read and map write
2021-12-17T18:15:42.8029105Z 
2021-12-17T18:15:42.8029940Z goroutine 566 [running]:
2021-12-17T18:15:42.8031106Z runtime.throw({0xad8696, 0xbbc210})
2021-12-17T18:15:42.8032688Z 	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1198 +0x71 fp=0xc000cf7990 sp=0xc000cf7960 pc=0x435d91
2021-12-17T18:15:42.8034224Z runtime.mapaccess1_faststr(0x3, 0xc0004f3680, {0xc000cba230, 0x47})
2021-12-17T18:15:42.8036332Z 	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/map_faststr.go:21 +0x3a5 fp=0xc000cf79f8 sp=0xc000cf7990 pc=0x413f65
2021-12-17T18:15:42.8038956Z github.com/estesp/manifest-tool/v2/pkg/store.(*MemoryStore).Info(0x …
```
> read lock added to fix unsafe concurrent read

- v2/pkg/registry/push.go
- v2/pkg/registry/pusher.go
Both GCR and Quay have a potentially different auth flow and hit a known
issue with "body reuse" in the push operation to a repo that is "public
pull" but "auth push". This works around it with a retry in this
specific case until containerd has a solution.
Fixes: #122 
Fixes: #156
> Workaround for body reuse/401 auth errors

- .github/workflows/ci.yml
- .github/workflows/release.yml
Update to latest Go and add missing Go install in release action to
correct breaking code (default Go version too low in Actions)
> Update Go to 1.17.8

- v2/cmd/manifest-tool/inspect.go
- v2/cmd/manifest-tool/main.go
- v2/cmd/manifest-tool/push.go
Closes: #163 
Fixes a segmentation fault if a file was passed in to --docker-cfg
instead of a directory (which was expected). Now allows a path or a file
to be specified via the flag and updated the help text appropriately.
> Fix segv with docker-cfg flag and allow custom files

- v2/pkg/registry/push.go
Provides detailed information about which image reference mismatches
to enable users to more easily recognize what they need to correct.
fixes #171
> Reword registry mismatch message

- .github/workflows/ci.yml
10.15 will be deprecated soon in GitHub Actions.
> Update macos version in Actions to 12

- .github/workflows/ci.yml
- .github/workflows/release.yml
- v2/cmd/manifest-tool/main.go
- v2/go.mod
- v2/go.sum
- v2/vendor/github.com/containerd/containerd/remotes/docker/auth/parse.go
- v2/vendor/github.com/containerd/containerd/version/version.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- v2/vendor/github.com/opencontainers/image-spec/specs-go/version.go
- v2/vendor/modules.txt
Commits for:
- updating Go version to 1.19.2
- updating GH Actions runner on Linux to `ubuntu-20.04`
- updating major vendors to latest releases
- set version string for v2.0.6 release
> Prepare v2.0.6 release

- README.md
- v2/cmd/manifest-tool/push.go
Only `from-spec` subcommand allowed specifying extra tags for manifest list, but this is not convinient to create or modify manifest YAML during CI.
This PR adds additional `--tags` argument to `from-args` subcommand to specify tags via command-line without touching/creating/modifying manifest during CI.
Also this PR includes minor refactoring to required cli args and adds an example to README.md
> Ability to specify additional tags via from-args subcommand

- v2/pkg/util/resolver.go
Docker's login command adds "index.docker.io" as the reference for storing DockerHub login credentials.
> Properly handle docker.io resolution for auth

- v2/pkg/registry/push.go
- v2/pkg/registry/pusher.go
Simple initial implementation of preserving attestations that exist in source images in the final manifest list/index.
Fixes: #199 
This solves #199 specifically, but I want to clean this up some more; it's a bit brittle at the moment. I would rather make this flexibly support combining two different indexes (merging platforms and attestations, for example).
> Preserve attestations with images

- .github/workflows/ci.yml
- integration/common-setup.bash
- integration/local-registry-tests-tls.bats
- integration/local-registry-tests.bats
- integration/public-registry-tests.bats
A long time coming, but we need tests to validate functionality on each PR/release. This is just the barebones start of a framework of tests against public registries and local registries and needs to be expanded to cover most of the inspect and
push capabilities over time.
> Add BATS-based integration framework

- v2/cmd/manifest-tool/inspect.go
- v2/pkg/registry/push.go
- v2/pkg/util/resolver.go
Update to use the `Hosts` resolver configuration style and remove use of deprecated constructs
> Migrate to Hosts from deprecated resolver config

- hack/Dockerfile.alpine
Add the GCR, ACR, and ECR credential helpers to the manifest-tool alpine-based image
> Add credential helpers to Alpine image

- hack/Dockerfile.alpine
Hello, thanks for creating this tool. It's been helpful for our CI/CD processes. 
I am submitted this PR with two fixes that we found helpful. 
* Change `bld` to use `TARGETARCH` as we would want the from source arch to be same as the target. 
* Changing google auth helper to be named `/usr/bin/docker-credential-gcloud`. When using the gcloud helper command `gcloud auth configure-docker <gcr-or-gar>` the resulting docker config file is looking for `docker-credentials-gcloud`. 
Example docker config:
```
{
"auths": {},
"credsStore": "desktop",
"credHelpers": {
"asia.gcr.io": "gcloud",
"eu.gcr.io": "gcloud",
"gcr.io": "gcloud",
"marketplace.gcr.io": "gcloud",
"staging-k8s.gcr.io": "gcloud",
"us.gcr.io": "gcloud",
},
"currentContext": "desktop-linux"
}
```
> fix(Dockerfile.alpine): gcloud auth naming and targetarch from alpine

- hack/Dockerfile.alpine
- v2/cmd/manifest-tool/main.go
Needed some more changes to the Alpine variant Dockerfile to make it appropriately cross-compile as the release scripts built from amd64 hardware platform so using $TARGETARCH doesn't work properly.
> Allow better cross-compilation of added cred helpers

- hack/Dockerfile.alpine
- v2/cmd/manifest-tool/main.go
> Fix Alpine+credential helpers image generation (again)

- .github/workflows/release.yml
- hack/Dockerfile.alpine
- Update to latest Go release
- Update actions to latest versions
- Update GCR auth helper to v2
- Update Alpine to 3.20.x
> Update release automation

- integration/common-setup.bash
Now that single-arch images are indexes (because of attestations) provide the --platform flag to only pull the required arch image
> Fix local pull of prep images

- integration/local-registry-tests.bats
- v2/cmd/manifest-tool/inspect.go
- v2/cmd/manifest-tool/push.go
This fixes an issue where certain error paths were not actually returning error and the binary was exiting with zero (success) instead of failure.
Also removed all `logrus.Fatal()` and moved them to returns of `fmt.Errorf()` and use `%w` for wrapping.
Fixes: #279
> Clean up error handling/returns

- integration/test-registry.yml
- v2/cmd/manifest-tool/push.go
- v2/pkg/registry/push.go
- v2/pkg/registry/pusher.go
- v2/pkg/types/input.go
- v2/pkg/types/manifests.go
Fixes: #282 
Closes: #263 
OCI indexes support annotations and many tools/registries recommend and use the standard OCI org annotations to improve metadata visibility of images. With these changes manifest-tool will properly push annotations either as command line options or included in the YAML (the example YAML in the repo is updated to show this as well).
Since the official Docker v2 manifestList schema does not support annotations at the manifestList level (only on the manifests themselves) this tool will error out if you try and submit annotations but don't use the "--type oci" flag on the command line.
> Add support for adding annotations to OCI indexes
